### ISSUE TITLE
occ_count parameter change

### ISSUE THREAD

**Issue by johnbaums** [ropensci/rgbif#386]
`occ_count` now requires `TRUE` to be passed as the lower case string, `'true'`. 

``` r
library(rgbif)
# example from ?occ_count:
occ_count(taxonKey=2435099, georeferenced=TRUE)
#> Registered S3 method overwritten by 'crul':
#>   method                 from
#>   as.character.form_file httr
#> Error: <html>
#> <head>
#> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
#> <title>Error 500 Server Error</title>
#> </head>
#> <body><h2>HTTP ERROR 500</h2>
#> <p>Problem accessing /occurrence/count. Reason:
#> <pre>    Server Error</pre></p><h3>Caused by:</h3><pre>org.cache2k.integration.CacheLoaderException: expiry=2019-12-10 10:54:23.77, cause: ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]
#>  at org.cache2k.core.StandardExceptionPropagator.propagateException(StandardExceptionPropagator.java:48)
#>  at org.cache2k.core.HeapCache.returnValue(HeapCache.java:1256)
#>  at org.cache2k.core.HeapCache.get(HeapCache.java:552)
#>  at org.gbif.metrics.es.EsMetricsService.count(EsMetricsService.java:218)
#>  at org.gbif.metrics.ws.resources.OccurrenceCubeResource.count(OccurrenceCubeResource.java:55)
#>  at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:498)
#>  at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
#>  at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
#>  at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
#>  at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
#>  at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
#>  at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
#>  at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
#>  at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
#>  at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
#>  at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
#>  at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
#>  at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
#>  at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
#>  at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
#>  at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
#>  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
#>  at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
#>  at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
#>  at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
#>  at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
#>  at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
#>  at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
#>  at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
#>  at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
#>  at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
#>  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
#>  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
#>  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
#>  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
#>  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
#>  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
#>  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
#>  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
#>  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
#>  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
#>  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
#>  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
#>  at org.eclipse.jetty.server.Server.handle(Server.java:539)
#>  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
#>  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
#>  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
#>  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
#>  at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
#>  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
#>  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
#>  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
#>  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
#>  at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
#>  at java.lang.Thread.run(Thread.java:748)
#> Caused by: ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]
#>  at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
#>  at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2050)
#>  at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2026)
#>  at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1775)
#>  at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1732)
#>  at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1694)
#>  at org.elasticsearch.client.RestHighLevelClient.count(RestHighLevelClient.java:972)
#>  at org.gbif.metrics.es.EsMetricsService.loadCount(EsMetricsService.java:106)
#>  at org.gbif.metrics.es.EsMetricsService.access$000(EsMetricsService.java:41)
#>  at org.gbif.metrics.es.EsMetricsService$1.load(EsMetricsService.java:82)
#>  at org.gbif.metrics.es.EsMetricsService$1.load(EsMetricsService.java:79)
#>  at org.cache2k.core.InternalCache2kBuilder$1.load(InternalCache2kBuilder.java:117)
#>  at org.cache2k.core.HeapCache.load(HeapCache.java:1363)
#>  at org.cache2k.core.HeapCache.getEntryInternal(HeapCache.java:652)
#>  at org.cache2k.core.HeapCache.getEntryInternal(HeapCache.java:624)
#>  at org.cache2k.core.HeapCache.get(HeapCache.java:548)
#>  ... 54 more
#>  Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://c6n4.gbif.org:9200], URI [/occurrence/_count?ignore_unavailable=false&amp;expand_wildcards=open&amp;allow_no_indices=true], status line [HTTP/1.1 400 Bad Request]
#> {&quot;error&quot;:{&quot;root_cause&quot;:[{&quot;type&quot;:&quot;query_shard_exception&quot;,&quot;reason&quot;:&quot;failed to create query: {\n  \&quot;bool\&quot; : {\n    \&quot;filter\&quot; : [\n      {\n        \&quot;term\&quot; : {\n          \&quot;gbifClassification.taxonKey\&quot; : {\n            \&quot;value\&quot; : \&quot;2435099\&quot;,\n            \&quot;boost\&quot; : 1.0\n          }\n        }\n      },\n      {\n        \&quot;term\&quot; : {\n          \&quot;hasCoordinate\&quot; : {\n            \&quot;value\&quot; : \&quot;TRUE\&quot;,\n            \&quot;boost\&quot; : 1.0\n          }\n        }\n      }\n    ],\n    \&quot;adjust_pure_negative\&quot; : true,\n    \&quot;boost\&quot; : 1.0\n  }\n}&quot;,&quot;index_uuid&quot;:&quot;D0Ub7nGyQVO67A_fmuiNIA&quot;,&quot;index&quot;:&quot;02d1e772-54ee-4767-b4b8-c35f0c7270ba_104_201911131446_1573666851389&quot;},{&quot;type&quot;:&quot;query_shard_exception&quot;,&quot;reason&quot;:&quot;failed to create query: {\n  \&quot;bool\


occ_count(taxonKey=2435099, georeferenced='true')
#> [1] 6269
```

<sup>Created on 2019-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

<details>

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       macOS Mojave 10.14.3        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_AU.UTF-8                 
#>  ctype    en_AU.UTF-8                 
#>  tz       Australia/Melbourne         
#>  date     2019-12-10                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [2] CRAN (R 3.6.0)
#>  cli           1.1.0   2019-03-19 [2] CRAN (R 3.6.0)
#>  colorspace    1.4-1   2019-03-18 [2] CRAN (R 3.6.0)
#>  crayon        1.3.4   2017-09-16 [2] CRAN (R 3.6.0)
#>  crul          0.8.4   2019-08-02 [1] CRAN (R 3.6.0)
#>  curl          4.2     2019-09-24 [2] CRAN (R 3.6.0)
#>  data.table    1.12.2  2019-04-07 [1] CRAN (R 3.6.0)
#>  digest        0.6.22  2019-10-21 [1] CRAN (R 3.6.0)
#>  dplyr         0.8.3   2019-07-04 [2] CRAN (R 3.6.0)
#>  evaluate      0.14    2019-05-28 [2] CRAN (R 3.6.0)
#>  geoaxe        0.1.0   2016-02-19 [2] CRAN (R 3.6.0)
#>  ggplot2       3.2.1   2019-08-10 [2] CRAN (R 3.6.0)
#>  glue          1.3.1   2019-03-12 [2] CRAN (R 3.6.0)
#>  gtable        0.3.0   2019-03-25 [2] CRAN (R 3.6.0)
#>  highr         0.8     2019-03-20 [2] CRAN (R 3.6.0)
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.0)
#>  httpcode      0.2.0   2016-11-14 [2] CRAN (R 3.6.0)
#>  httr          1.4.1   2019-08-05 [2] CRAN (R 3.6.0)
#>  jsonlite      1.6     2018-12-07 [2] CRAN (R 3.6.0)
#>  knitr         1.25    2019-09-18 [1] CRAN (R 3.6.0)
#>  lattice       0.20-38 2018-11-04 [2] CRAN (R 3.6.0)
#>  lazyeval      0.2.2   2019-03-15 [2] CRAN (R 3.6.0)
#>  magrittr      1.5     2014-11-22 [2] CRAN (R 3.6.0)
#>  munsell       0.5.0   2018-06-12 [2] CRAN (R 3.6.0)
#>  oai           0.3.0   2019-09-07 [1] CRAN (R 3.6.0)
#>  pillar        1.4.2   2019-06-29 [2] CRAN (R 3.6.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.0)
#>  plyr          1.8.4   2016-06-08 [2] CRAN (R 3.6.0)
#>  purrr         0.3.3   2019-10-18 [1] CRAN (R 3.6.0)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.0)
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.0)
#>  rgbif       * 1.4.0   2019-10-30 [1] CRAN (R 3.6.0)
#>  rgeos         0.5-1   2019-08-05 [1] CRAN (R 3.6.0)
#>  rlang         0.4.1   2019-10-24 [1] CRAN (R 3.6.0)
#>  rmarkdown     1.16    2019-10-01 [1] CRAN (R 3.6.0)
#>  scales        1.0.0   2018-08-09 [2] CRAN (R 3.6.0)
#>  sessioninfo   1.1.1   2018-11-05 [2] CRAN (R 3.6.0)
#>  sp            1.3-1   2018-06-05 [2] CRAN (R 3.6.0)
#>  stringi       1.4.3   2019-03-12 [2] CRAN (R 3.6.0)
#>  stringr       1.4.0   2019-02-10 [2] CRAN (R 3.6.0)
#>  tibble        2.1.3   2019-06-06 [2] CRAN (R 3.6.0)
#>  tidyselect    0.2.5   2018-10-11 [2] CRAN (R 3.6.0)
#>  triebeard     0.3.0   2016-08-04 [2] CRAN (R 3.6.0)
#>  urltools      1.7.3   2019-04-14 [2] CRAN (R 3.6.0)
#>  whisker       0.4     2019-08-28 [1] CRAN (R 3.6.0)
#>  withr         2.1.2   2018-03-15 [2] CRAN (R 3.6.0)
#>  xfun          0.10    2019-10-01 [1] CRAN (R 3.6.0)
#>  xml2          1.2.2   2019-08-09 [2] CRAN (R 3.6.0)
#>  yaml          2.2.0   2018-07-25 [2] CRAN (R 3.6.0)
#> 
#> [1] /Users/jbau/Library/R/3.6/library
#> [2] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by sckott** [comment]
thanks @johnbaums !

try the dev version `remotes::install_github("ropensci/rgbif")` - it was just fixed about a week ago ce16bde
